# Generated by Django 5.2.6 on 2025-12-04 22:23

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('max_events', models.IntegerField(default=50)),
                ('max_push_per_day', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Piano Alert',
                'verbose_name_plural': 'Piani Alert',
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField()),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('SOLD_OUT', 'SoldOut'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'InventorySnapshot',
                'verbose_name_plural': 'InventorySnapshots',
            },
        ),
        migrations.CreateModel(
            name='Piattaforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=60, unique=True)),
                ('dominio', models.CharField(blank=True, max_length=120, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Piattaforma',
                'verbose_name_plural': 'Piattaforme',
            },
        ),
        migrations.CreateModel(
            name='Sconti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata_mesi', models.IntegerField()),
                ('percentuale', models.IntegerField()),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sconto',
                'verbose_name_plural': 'Sconti',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero di telefono')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('gender', models.CharField(choices=[('male', 'Maschio'), ('female', 'Femmina'), ('other', 'Altro'), ('na', 'Preferisco non dirlo')], default='na', max_length=20, verbose_name='Sesso')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='Nazione')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Città')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('document_id', models.CharField(blank=True, help_text="Codice del documento d'identità", max_length=50, null=True, verbose_name='Codice documento')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notifiche email')),
                ('notify_whatsapp', models.BooleanField(default=False, verbose_name='Notifiche wahtsapp')),
                ('notify_push', models.BooleanField(default=True, verbose_name='Notifiche push')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='Termini accettati')),
                ('accepted_privacy', models.BooleanField(default=False, verbose_name='Privacy accettata')),
                ('gdpr_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data accettazione GDPR')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data eliminazione')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Data ultimo accesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ultimo aggiornamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Abbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_inizio', models.DateTimeField(auto_now_add=True)),
                ('data_fine', models.DateTimeField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbonamenti', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abbonamenti', to='api.alertplan', verbose_name='Piano Alert')),
                ('sconto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abbonamenti', to='api.sconti')),
            ],
            options={
                'verbose_name': 'Abbonamento',
                'verbose_name_plural': 'Abbonamenti',
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_normalizzato', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('artista', 'Artista'), ('squadra', 'Squadra'), ('atleta', 'Atleta'), ('altro', 'Altro')], default='artista', max_length=7)),
                ('nomi_alternativi', models.JSONField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artisti',
                'indexes': [models.Index(fields=['nome'], name='api_artista_nome_a8c7a8_idx'), models.Index(fields=['nome_normalizzato'], name='api_artista_nome_no_59bde6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=60, unique=True)),
                ('nome', models.CharField(default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'indexes': [models.Index(fields=['nome'], name='api_categor_nome_a0792b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=255, unique=True)),
                ('nome_evento', models.CharField(default='', max_length=255)),
                ('nome_evento_normalizzato', models.CharField(default='', max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('pianificato', 'Pianificato'), ('annullato', 'Annullato'), ('rinviato', 'Rinviato'), ('riprogrammato', 'Riprogrammato')], default='pianificato', max_length=13)),
                ('genere', models.CharField(blank=True, max_length=120, null=True)),
                ('lingua', models.CharField(blank=True, max_length=40, null=True)),
                ('immagine_url', models.CharField(blank=True, max_length=512, null=True)),
                ('hash_canonico', models.CharField(default='', max_length=64, unique=True)),
                ('note_raw', models.JSONField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('artista_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_principali', to='api.artista')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi', to='api.categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
            },
        ),
        migrations.CreateModel(
            name='EventFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_follows', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Evento Seguito',
                'verbose_name_plural': 'Eventi Seguiti',
            },
        ),
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_file', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_intestatario', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.CharField(blank=True, db_index=True, help_text='Payload testuale letto dal QR/Barcode', max_length=255, null=True)),
                ('sigillo_fiscale', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('path_file', models.FileField(upload_to=api.models.biglietto_path)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('hash_file', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('pages_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tickets_found', models.PositiveSmallIntegerField(default=0, help_text='Quanti biglietti distinti trovati nel PDF')),
                ('extracted_names', models.JSONField(blank=True, help_text='Lista nominativi trovati (per scelta)', null=True)),
                ('extracted_prices', models.JSONField(blank=True, help_text='Prezzi letti, se presenti', null=True)),
                ('extracted_meta', models.JSONField(blank=True, help_text='Altri metadati: settore, fila, posto, ecc.', null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biglietti', to='api.evento')),
            ],
            options={
                'verbose_name': 'Biglietto',
                'verbose_name_plural': 'Biglietti',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_top', models.BooleanField(db_index=True, default=False)),
                ('seat_category', models.CharField(blank=True, max_length=80, null=True)),
                ('section', models.CharField(blank=True, max_length=80, null=True)),
                ('row', models.CharField(blank=True, max_length=40, null=True)),
                ('seat_from', models.IntegerField(blank=True, null=True)),
                ('seat_to', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('delivery_method', models.CharField(choices=[('E_TICKET', 'E_TICKET'), ('PDF', 'PDF'), ('COURIER', 'COURIER'), ('APP_TRANSFER', 'APP_TRANSFER')], default='PDF', max_length=12)),
                ('change_name_required', models.BooleanField(default=False, help_text='Se richiesto dalla piattaforma/tempi evento')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RESERVED', 'RESERVED'), ('SOLD', 'SOLD'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Liste',
            },
        ),
        migrations.CreateModel(
            name='ListingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biglietto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.biglietto')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
            ],
            options={
                'verbose_name': 'Lista Biglietto',
                'verbose_name_plural': 'Liste Biglietti',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='tickets',
            field=models.ManyToManyField(related_name='listings', through='api.ListingTicket', to='api.biglietto'),
        ),
        migrations.CreateModel(
            name='Luoghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('nome_normalizzato', models.CharField(default='', max_length=255)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('citta', models.CharField(blank=True, max_length=120, null=True)),
                ('citta_normalizzata', models.CharField(blank=True, max_length=120, null=True)),
                ('stato_iso', models.CharField(blank=True, max_length=2, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Luogo',
                'verbose_name_plural': 'Luoghi',
                'indexes': [models.Index(fields=['nome_normalizzato'], name='api_luoghi_nome_no_2b67d4_idx'), models.Index(fields=['citta_normalizzata'], name='api_luoghi_citta_n_916747_idx')],
                'constraints': [models.UniqueConstraint(fields=('nome_normalizzato',), name='uq_luoghi_nome_norm')],
            },
        ),
        migrations.CreateModel(
            name='Monitoraggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters_json', models.JSONField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('abbonamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoraggi', to='api.abbonamento')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoraggi', to='api.evento')),
            ],
            options={
                'verbose_name': 'Monitoraggio',
                'verbose_name_plural': 'Monitoraggi',
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('BACK_IN_STOCK', 'BackInStock'), ('PRICE_DROP', 'PriceDrop'), ('NEW_DATE', 'NewDate')], max_length=20)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='api.inventorysnapshot')),
                ('monitoraggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='api.monitoraggio')),
            ],
            options={
                'verbose_name': 'Trigger Alert',
                'verbose_name_plural': 'Triggers Alert',
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='push', max_length=10)),
                ('dedupe_key', models.CharField(blank=True, max_length=120, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=8)),
                ('message', models.TextField()),
                ('monitoraggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='api.monitoraggio')),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
            },
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('DELIVERED', 'DELIVERED'), ('REFUNDED', 'REFUNDED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.listing')),
            ],
            options={
                'verbose_name': 'Ordine Biglietto',
                'verbose_name_plural': 'Ordini Biglietti',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STRIPE', 'STRIPE'), ('PAYPAL', 'PAYPAL'), ('OTHER', 'OTHER')], default='STRIPE', max_length=12)),
                ('provider_intent_id', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('REQUIRES_ACTION', 'REQUIRES_ACTION'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='REQUIRES_ACTION', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.orderticket')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at_utc', models.DateTimeField()),
                ('ends_at_utc', models.DateTimeField(blank=True, null=True)),
                ('doors_at_utc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONSALE', 'OnSale'), ('SOLD_OUT', 'SoldOut'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('ENDED', 'Ended')], default='ONSALE', max_length=12)),
                ('disponibilita_agg', models.CharField(choices=[('disponibile', 'Disponibile'), ('limitata', 'Limitata'), ('non_disponibile', 'Non Disponibile'), ('sconosciuta', 'Sconosciuta')], default='sconosciuta', max_length=16)),
                ('prezzo_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prezzo_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valuta', models.CharField(blank=True, max_length=3, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.evento')),
                ('luogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.luoghi')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'ordering': ['-starts_at_utc'],
            },
        ),
        migrations.AddField(
            model_name='monitoraggio',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoraggi', to='api.performance'),
        ),
        migrations.AddField(
            model_name='listing',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.performance'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.performance'),
        ),
        migrations.AddField(
            model_name='biglietto',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biglietti', to='api.performance'),
        ),
        migrations.CreateModel(
            name='PerformancePiattaforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_perf_id', models.CharField(max_length=255)),
                ('url', models.CharField(default='', max_length=1024)),
                ('ultima_scansione', models.DateTimeField()),
                ('snapshot_raw', models.JSONField(blank=True, null=True)),
                ('checksum_dati', models.CharField(blank=True, max_length=64, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='api.performance')),
                ('piattaforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_performance', to='api.piattaforma')),
            ],
            options={
                'verbose_name': 'Performance Piattaforma',
                'verbose_name_plural': 'Performance Piattaforme',
            },
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='piattaforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.piattaforma'),
        ),
        migrations.CreateModel(
            name='EventoPiattaforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento_piattaforma', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(default='', max_length=1024)),
                ('ultima_scansione', models.DateTimeField()),
                ('snapshot_raw', models.JSONField(blank=True, null=True)),
                ('checksum_dati', models.CharField(blank=True, max_length=64, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_evento', to='api.evento')),
                ('piattaforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_evento', to='api.piattaforma')),
            ],
            options={
                'verbose_name': 'Evento Piattaforma',
                'verbose_name_plural': 'Evento Piattaforme',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recensioni_scritte', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recensioni', to='api.orderticket')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_ricevute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.CreateModel(
            name='Rivendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('disponibile', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('SOLD', 'SOLD'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=12)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('biglietto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivendite_biglietto', to='api.biglietto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivendite', to='api.evento')),
                ('venditore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rivendite_venditore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acquisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_corso', 'in_corso'), ('completato', 'completato'), ('rimborsato', 'rimborsato')], default='in_corso', max_length=12)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to=settings.AUTH_USER_MODEL)),
                ('rivendita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to='api.rivendita')),
            ],
            options={
                'verbose_name': 'Acquisto',
                'verbose_name_plural': 'Acquisti',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=api.models.support_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.supportmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DOWNLOAD', 'Problemi download biglietto'), ('NAMECHANGE', 'Cambio nominativo'), ('PAYMENT', 'Pagamento'), ('REFUND', 'Rimborso'), ('SELLING', 'Vendita / Annunci'), ('OTHER', 'Altro')], default='OTHER', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Bassa'), ('NORMAL', 'Normale'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Aperto'), ('PENDING', 'In attesa'), ('RESOLVED', 'Risolto'), ('CLOSED', 'Chiuso')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('biglietto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='api.biglietto')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='api.listing')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='api.orderticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.supportticket'),
        ),
        migrations.CreateModel(
            name='TicketSubitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('code_type', models.CharField(blank=True, max_length=20, null=True)),
                ('code_raw', models.TextField(blank=True, null=True)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('settore', models.CharField(blank=True, max_length=80, null=True)),
                ('fila', models.CharField(blank=True, max_length=40, null=True)),
                ('posto', models.CharField(blank=True, max_length=40, null=True)),
                ('is_listed', models.BooleanField(db_index=True, default=False)),
                ('is_sold', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biglietto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='api.biglietto')),
            ],
            options={
                'verbose_name': 'Sub-biglietto',
                'verbose_name_plural': 'Sub-biglietti',
            },
        ),
        migrations.AddField(
            model_name='rivendita',
            name='subitems',
            field=models.ManyToManyField(blank=True, related_name='rivendite', to='api.ticketsubitem'),
        ),
        migrations.CreateModel(
            name='ListingSubitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='api.listing')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.ticketsubitem')),
            ],
            options={
                'verbose_name': 'Listing Subitem',
                'verbose_name_plural': 'Listing Subitems',
            },
        ),
        migrations.CreateModel(
            name='TicketUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PARSING', 'PARSING'), ('READY', 'READY'), ('ERROR', 'ERROR')], default='PARSING', max_length=10)),
                ('found_count', models.IntegerField(default=0)),
                ('selectable_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biglietto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='api.biglietto')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Biglietto',
                'verbose_name_plural': 'Upload Biglietti',
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='api.ticketupload'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='api_userpro_email_4cfe15_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['document_id'], name='api_userpro_documen_c59803_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['nome_evento_normalizzato'], name='api_evento_nome_ev_250982_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['stato'], name='api_evento_stato_ca1356_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventfollow',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='uq_event_follow'),
        ),
        migrations.AddConstraint(
            model_name='listingticket',
            constraint=models.UniqueConstraint(fields=('listing', 'biglietto'), name='uq_listing_ticket'),
        ),
        migrations.AddIndex(
            model_name='alerttrigger',
            index=models.Index(fields=['triggered_at'], name='api_alerttr_trigger_9a41ff_idx'),
        ),
        migrations.AddIndex(
            model_name='notifica',
            index=models.Index(fields=['monitoraggio'], name='api_notific_monitor_beb8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='notifica',
            index=models.Index(fields=['dedupe_key'], name='api_notific_dedupe__de543c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderticket',
            index=models.Index(fields=['buyer', 'status'], name='api_orderti_buyer_i_530bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderticket',
            index=models.Index(fields=['created_at'], name='api_orderti_created_5e5513_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['evento', 'starts_at_utc'], name='api_perform_evento__bdd944_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['luogo', 'starts_at_utc'], name='api_perform_luogo_i_b68637_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['status'], name='api_perform_status_161310_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoraggio',
            constraint=models.CheckConstraint(condition=models.Q(('evento__isnull', False), ('performance__isnull', False), _connector='OR'), name='ck_monitoraggio_target'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['performance', 'status'], name='api_listing_perform_c392b4_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller'], name='api_listing_seller__879958_idx'),
        ),
        migrations.AddIndex(
            model_name='biglietto',
            index=models.Index(fields=['qr_code'], name='api_bigliet_qr_code_b41f90_idx'),
        ),
        migrations.AddIndex(
            model_name='biglietto',
            index=models.Index(fields=['sigillo_fiscale'], name='api_bigliet_sigillo_48a87c_idx'),
        ),
        migrations.AddIndex(
            model_name='biglietto',
            index=models.Index(fields=['hash_file'], name='api_bigliet_hash_fi_f651d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='biglietto',
            constraint=models.UniqueConstraint(condition=models.Q(('hash_file', None), _negated=True), fields=('hash_file',), name='uq_ticket_hash'),
        ),
        migrations.AddConstraint(
            model_name='biglietto',
            constraint=models.UniqueConstraint(condition=models.Q(('sigillo_fiscale', None), _negated=True), fields=('sigillo_fiscale',), name='uq_ticket_sigillo'),
        ),
        migrations.AddConstraint(
            model_name='biglietto',
            constraint=models.UniqueConstraint(condition=models.Q(('qr_code', None), _negated=True), fields=('qr_code',), name='uq_ticket_qr'),
        ),
        migrations.AddIndex(
            model_name='performancepiattaforma',
            index=models.Index(fields=['performance'], name='api_perform_perform_5f16d2_idx'),
        ),
        migrations.AddIndex(
            model_name='performancepiattaforma',
            index=models.Index(fields=['ultima_scansione'], name='api_perform_ultima__81815a_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancepiattaforma',
            constraint=models.UniqueConstraint(fields=('piattaforma', 'external_perf_id'), name='uq_perf_plat_external'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['performance', 'piattaforma', 'taken_at'], name='api_invento_perform_4ad5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventopiattaforma',
            index=models.Index(fields=['ultima_scansione'], name='api_eventop_ultima__b88d22_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventopiattaforma',
            constraint=models.UniqueConstraint(condition=models.Q(('id_evento_piattaforma', None), _negated=True), fields=('piattaforma', 'id_evento_piattaforma'), name='uq_evento_plat_external'),
        ),
        migrations.AddConstraint(
            model_name='eventopiattaforma',
            constraint=models.UniqueConstraint(fields=('evento', 'piattaforma'), name='uq_evento_plat_pair'),
        ),
        migrations.AddIndex(
            model_name='recensione',
            index=models.Index(fields=['venditore'], name='api_recensi_vendito_95f544_idx'),
        ),
        migrations.AddIndex(
            model_name='recensione',
            index=models.Index(fields=['acquirente'], name='api_recensi_acquire_7b6039_idx'),
        ),
        migrations.AddConstraint(
            model_name='recensione',
            constraint=models.UniqueConstraint(fields=('order', 'acquirente'), name='uq_review_per_order_author'),
        ),
        migrations.AddConstraint(
            model_name='listingsubitem',
            constraint=models.UniqueConstraint(fields=('listing', 'subitem'), name='uq_listing_subitem'),
        ),
    ]
