# Generated by Django 5.2.4 on 2025-07-22 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('artista', models.CharField(max_length=255)),
                ('data_ora', models.DateTimeField()),
                ('luogo', models.CharField(max_length=255)),
                ('città', models.CharField(max_length=100)),
                ('url_immagine', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('concerto', 'Concerto'), ('teatro', 'Teatro'), ('sport', 'Sport'), ('altro', 'Altro')], max_length=50)),
                ('stato_disponibilità', models.CharField(choices=[('disponibile', 'Disponibile'), ('sold_out', 'Sold Out')], default='disponibile', max_length=20)),
                ('attivo', models.BooleanField(default=True)),
                ('timestamp_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_ora'],
            },
        ),
        migrations.CreateModel(
            name='Piattaforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('url_base', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Piattaforme',
            },
        ),
        migrations.CreateModel(
            name='EventoPiattaforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pagina_evento', models.URLField()),
                ('disponibilità_biglietti', models.CharField(choices=[('disponibile', 'Disponibile'), ('sold_out', 'Sold Out')], default='disponibile', max_length=20)),
                ('prezzo_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('timestamp_aggiornamento', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piattaforme_collegate', to='api.evento')),
                ('piattaforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_collegati', to='api.piattaforma')),
            ],
            options={
                'unique_together': {('evento', 'piattaforma')},
            },
        ),
    ]
