# Generated by Django 5.2.4 on 2025-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento_piattaforma_eventopiattaforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_biglietto', models.CharField(max_length=5)),
                ('titolo', models.CharField(blank=True, max_length=255)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('path_file', models.FileField(upload_to='uploads/%Y/%m/%d/%H')),
            ],
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='città',
            new_name='citta',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='stato_disponibilità',
            new_name='stato_disponibilita',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
