# Generated by Django 5.2.6 on 2026-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orderticket_holder_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='api_pushdev_utente__14416f_idx',
            old_name='api_pushdev_utente_i_idx',
        ),
        migrations.RemoveField(
            model_name='alertplan',
            name='max_events',
        ),
        migrations.RemoveField(
            model_name='alertplan',
            name='max_push_per_day',
        ),
        migrations.AddField(
            model_name='abbonamento',
            name='mesi',
            field=models.IntegerField(blank=True, help_text="Numero mesi (0 per tipo 'evento')", null=True),
        ),
        migrations.AddField(
            model_name='abbonamento',
            name='periodo',
            field=models.CharField(blank=True, help_text="Es: '1m', '3m', '12m', 'evento'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alertplan',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'PRO')], default='FREE', help_text='Tipo di piano: Free o PRO', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_ok',
            field=models.BooleanField(default=False, verbose_name='Accetta marketing'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='x_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='X (Twitter) URL'),
        ),
    ]
