# Generated by Django 5.2.6 on 2026-07-15 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_api_pushdev_utente_i_idx_api_pushdev_utente__14416f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
    ]
