# Generated by Django 5.2.6 on 2026-07-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticketsubitem_sold_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='biglietto',
            name='auto_delivery_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biglietto',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_files', to='api.biglietto'),
        ),
        migrations.AddField(
            model_name='ticketsubitem',
            name='physical_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
